# K fold cross validation 

#### K-Fold Cross Validation is a technique used in machine learning to evaluate how well a model performs on unseen data. It helps in reducing overfitting and gives a more accurate estimate of model performance

## How it Works:
Split the dataset into K equal parts (folds).

For each fold:

- Use that fold as the validation set.
- Use the remaining K-1 folds as the training set.
- Train and evaluate the model K times.
- Average the results (accuracy, error, etc.) across all K runs.

In [1]:

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier
import numpy as np 
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
X = digits.data
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]], shape=(1797, 64))

In [3]:
y = digits.target
y

array([0, 1, 2, ..., 8, 9, 8], shape=(1797,))

In [4]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

**Logistic Regression**

In [5]:
lr = LogisticRegression(max_iter=500)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=500)

In [6]:
lr.score(X_test,y_test)

0.9703703703703703

**SVM**

In [7]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)

SVC(gamma='auto')

In [8]:
svm.score(X_test, y_test)

0.3925925925925926

**Random Forest**

In [9]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=40)

In [10]:
rf.score(X_test, y_test)

0.9685185185185186

# K Fold cross Validation

In [11]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
## for basic example
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [23]:
def get_score(model , X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test,y_test)

In [14]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [24]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    scores_logistic.append(get_score(LogisticRegression(solver='liblinear'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))


In [25]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [26]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [27]:
scores_rf

[0.9265442404006677, 0.9482470784641068, 0.9248747913188647]

## cross_val_score function

In [28]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [31]:
cross_val_score(LogisticRegression(max_iter = 500), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

**svm model performance using cross_val_score**

In [33]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

**random forest performance using cross_val_score**

In [34]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target)

array([0.93611111, 0.91388889, 0.95821727, 0.96100279, 0.9275766 ])

## Parameter Tuning using K Fold

In [35]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

np.float64(0.8820360024829297)

In [36]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

np.float64(0.9365797641216635)

In [37]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

np.float64(0.9482526381129732)

In [38]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

np.float64(0.9471446306641835)

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 30 trees in random forest gives best result.