# Exercise 

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

- Logistic Regression
- SVM
- Decision Tree
- Random Forest

### IRIS classification using k fold cross validation 

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np 
from sklearn.datasets import load_iris
iris = load_iris()
import pandas as pd

In [18]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [19]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [5]:
X = df.drop('target', axis = 'columns')
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
y = df['target']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size = 0.2)

**Logistic Regression**

In [8]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [9]:
lr.score(X_test,y_test)

0.9333333333333333

**Decision Tree**

In [23]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [24]:
dt.score(X_test, y_test)

0.9333333333333333

**Support Vector Machine (SVM)**

In [10]:
svm = SVC()
svm.fit(X_train, y_train)

SVC()

In [11]:
svm.score(X_test,y_test)

0.9333333333333333

**Random Forest**

In [12]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [13]:
rf.score(X_test,y_test)

0.9333333333333333

### Using Cross_val_score function 

In [15]:
from sklearn.model_selection import cross_val_score

**Logistic Regression using cross_val_score**

In [26]:
lr_scores = cross_val_score(LogisticRegression(max_iter = 500), iris.data, iris.target)
lr_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [27]:
np.average(lr_scores)

np.float64(0.9733333333333334)

**Decision tree using cross_val_score**

In [29]:
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [30]:
np.average(dt_scores)

np.float64(0.9533333333333334)

**SVM using cross_val_score**

In [31]:
svm_scores = cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [32]:
np.average(svm_scores)

np.float64(0.9666666666666666)

**Random Forest using cross_val_score function**

In [33]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [34]:
np.average(rf_scores)

np.float64(0.9533333333333334)

Hence Best score is from Logistic Regression 